### ISSUE TITLE
spike: remove types in gl.go and replace with client/*.go 

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/accounts#26]
Brooke mentioned removing the types in [gl.go](https://github.com/moov-io/gl/blob/master/gl.go) don't offer much and are confusing for Go callers with [types in the generated client/](https://github.com/moov-io/gl/tree/master/client). 

We should try removing the `"gl.go"` types and only use structs from `client/`. The client types are documented better and any restructure of data for performance / business logic should use unexported structs anyway.

I don't think this causes an import loop either. Just need to try and see! (Then do it for all apps)

**Comment by bkmoovio** [comment]
Running generate go-server creates the same model(s) in cmd/server

**Comment by adamdecaf** [comment]
I did this when renaming from GL.
