### ISSUE TITLE
Rename Project from GL to Accounts

### ISSUE THREAD

**Issue by wadearnold** [moov-io/accounts#44]
This project is designed to provide `accounts` and does it by being a general ledger (GL) so that it can facilitate transactions. I believe that it would be more self-explanatory if we used the term `Accounts` rather than GL when leveraging the different Moov projects. Thoughts?

**Comment by adamdecaf** [comment]
Yea. I'm fine with the name change.

**Comment by adamdecaf** [comment]
https://github.com/moov-io/api/commit/78a036a0908aef03579ffa2d4a415531d2eff4fb was part too
